name: Notify Render Deploy

on:
  push:
    branches:
      - main

jobs:
  trigger-render:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
